# SPDX-License-Identifier: GPL-2.0
#
# Makefile for nettrace.
#
nettrace-objs	:= core.o kprobe.o parser.o dump.o help.o group.o handler.o procfs.o utils.o mm.o
obj-$(CONFIG_NET_TRACE)			+= nettrace.o

