// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#include "nbl_ppe_ipro.h"
#include "nbl_ppe_epro.h"
#include "nbl_ppe_pp0.h"
#include "nbl_ppe_pp1.h"
#include "nbl_ppe_pp2.h"
#include "nbl_ppe_fem.h"
#include "nbl_ppe_mcc.h"
#include "nbl_ppe_acl.h"
#include "nbl_ppe_cap.h"
#include "nbl_ppe_uprbac.h"
#include "nbl_ppe_dprbac.h"
