// Code generated by interstellar. DO NOT EDIT.
// Compatible with leonis RTL tag 0710

#ifndef NBL_PCOMPLETER_ECPU_H
#define NBL_PCOMPLETER_ECPU_H 1

#include <linux/types.h>

#define NBL_PCOMPLETER_ECPU_BASE (0x01008000)

#define NBL_PCOMPLETER_ECPU_INT_STATUS_ADDR  (0x1008000)
#define NBL_PCOMPLETER_ECPU_INT_STATUS_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_INT_STATUS_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_INT_STATUS_DWLEN (1)
union pcompleter_ecpu_int_status_u {
	struct pcompleter_ecpu_int_status {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RWC */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RWC */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RWC */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RWC */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RWC */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RWC */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RWC */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_INT_STATUS_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_INT_MASK_ADDR  (0x1008004)
#define NBL_PCOMPLETER_ECPU_INT_MASK_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_INT_MASK_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_INT_MASK_DWLEN (1)
union pcompleter_ecpu_int_mask_u {
	struct pcompleter_ecpu_int_mask {
		u32 fatal_err:1;         /* [00:00] Default:0x0 RW */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 RW */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 RW */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 RW */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 RW */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 RW */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 RW */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_INT_MASK_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_INT_SET_ADDR  (0x1008008)
#define NBL_PCOMPLETER_ECPU_INT_SET_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_INT_SET_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_INT_SET_DWLEN (1)
union pcompleter_ecpu_int_set_u {
	struct pcompleter_ecpu_int_set {
		u32 fatal_err:1;         /* [00:00] Default:0x0 WO */
		u32 fifo_uflw_err:1;     /* [01:01] Default:0x0 WO */
		u32 fifo_dflw_err:1;     /* [02:02] Default:0x0 WO */
		u32 rsv3:1;              /* [03:03] Default:0x0 RO */
		u32 cif_err:1;           /* [04:04] Default:0x0 WO */
		u32 rsv2:1;              /* [05:05] Default:0x0 RO */
		u32 cfg_err:1;           /* [06:06] Default:0x0 WO */
		u32 data_ucor_err:1;     /* [07:07] Default:0x0 WO */
		u32 data_cor_err:1;      /* [08:08] Default:0x0 WO */
		u32 rsv1:1;              /* [09:09] Default:0x0 RO */
		u32 rsv:22;              /* [31:10] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_INT_SET_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_INIT_DONE_ADDR  (0x100800c)
#define NBL_PCOMPLETER_ECPU_INIT_DONE_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_INIT_DONE_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_INIT_DONE_DWLEN (1)
union pcompleter_ecpu_init_done_u {
	struct pcompleter_ecpu_init_done {
		u32 done:1;              /* [00:00] Default:0x1 RO */
		u32 rsv:31;              /* [31:01] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_INIT_DONE_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CIF_ERR_INFO_ADDR  (0x1008040)
#define NBL_PCOMPLETER_ECPU_CIF_ERR_INFO_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CIF_ERR_INFO_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CIF_ERR_INFO_DWLEN (1)
union pcompleter_ecpu_cif_err_info_u {
	struct pcompleter_ecpu_cif_err_info {
		u32 addr:30;             /* [29:00] Default:0x0 RO */
		u32 wr_err:1;            /* [30:30] Default:0x0 RO */
		u32 ucor_err:1;          /* [31:31] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CIF_ERR_INFO_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CAR_CTRL_ADDR  (0x1008100)
#define NBL_PCOMPLETER_ECPU_CAR_CTRL_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CAR_CTRL_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CAR_CTRL_DWLEN (1)
union pcompleter_ecpu_car_ctrl_u {
	struct pcompleter_ecpu_car_ctrl {
		u32 sctr_car:1;          /* [00:00] Default:0x1 RW */
		u32 rctr_car:1;          /* [01:01] Default:0x1 RW */
		u32 rc_car:1;            /* [02:02] Default:0x1 RW */
		u32 tbl_rc_car:1;        /* [03:03] Default:0x1 RW */
		u32 rsv:28;              /* [31:04] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CAR_CTRL_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_DATA_BIG_END_ADDR  (0x10090a0)
#define NBL_PCOMPLETER_ECPU_DATA_BIG_END_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_DATA_BIG_END_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_DATA_BIG_END_DWLEN (1)
union pcompleter_ecpu_data_big_end_u {
	struct pcompleter_ecpu_data_big_end {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 Rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_DATA_BIG_END_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CIF_AXI_BASE_ADDR  (0x10090f4)
#define NBL_PCOMPLETER_ECPU_CIF_AXI_BASE_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CIF_AXI_BASE_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CIF_AXI_BASE_DWLEN (1)
union pcompleter_ecpu_cif_axi_base_u {
	struct pcompleter_ecpu_cif_axi_base {
		u32 addr:32;             /* [31:0] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CIF_AXI_BASE_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_OPROM_OFFSET_ADDR  (0x10090f8)
#define NBL_PCOMPLETER_ECPU_CFG_OPROM_OFFSET_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_OPROM_OFFSET_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_OPROM_OFFSET_DWLEN (1)
union pcompleter_ecpu_cfg_oprom_offset_u {
	struct pcompleter_ecpu_cfg_oprom_offset {
		u32 addr:32;             /* [31:0] Default:0x4000000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_OPROM_OFFSET_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MSG_CLR_INT_ADDR  (0x1009104)
#define NBL_PCOMPLETER_ECPU_MSG_CLR_INT_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MSG_CLR_INT_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MSG_CLR_INT_DWLEN (1)
union pcompleter_ecpu_msg_clr_int_u {
	struct pcompleter_ecpu_msg_clr_int {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 Rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MSG_CLR_INT_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_AXI_READY_ADDR  (0x1009108)
#define NBL_PCOMPLETER_ECPU_AXI_READY_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_AXI_READY_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_AXI_READY_DWLEN (1)
union pcompleter_ecpu_axi_ready_u {
	struct pcompleter_ecpu_axi_ready {
		u32 overtime:32;         /* [31:0] Default:0x5fffff RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_AXI_READY_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR0_ADDR  (0x1009120)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR0_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR0_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR0_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr0_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr0 {
		u32 dbg:32;              /* [31:00] Default:0x01110000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR0_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR1_ADDR  (0x1009124)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR1_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR1_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR1_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr1_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr1 {
		u32 dbg:32;              /* [31:00] Default:0x00400000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR1_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR2_ADDR  (0x1009128)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR2_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR2_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR2_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr2_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr2 {
		u32 dbg:32;              /* [31:00] Default:0x011A0000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR2_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR3_ADDR  (0x100912c)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR3_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR3_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR3_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr3_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr3 {
		u32 dbg:32;              /* [31:00] Default:0x011A0000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR3_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR4_ADDR  (0x1009130)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR4_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR4_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR4_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr4_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr4 {
		u32 dbg:32;              /* [31:00] Default:0x011A0000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR4_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR5_ADDR  (0x1009134)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR5_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR5_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR5_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr5_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr5 {
		u32 dbg:32;              /* [31:00] Default:0x011A0000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR5_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR6_ADDR  (0x1009138)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR6_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR6_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR6_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr6_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr6 {
		u32 dbg:32;              /* [31:00] Default:0x01110000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR6_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR7_ADDR  (0x100913c)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR7_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR7_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR7_DWLEN (1)
union pcompleter_ecpu_cfg_rdma_base_addr7_u {
	struct pcompleter_ecpu_cfg_rdma_base_addr7 {
		u32 dbg:32;              /* [31:00] Default:0x01110000 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_RDMA_BASE_ADDR7_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_OPROM_DEBUG_ADDR  (0x1009160)
#define NBL_PCOMPLETER_ECPU_OPROM_DEBUG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_OPROM_DEBUG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_OPROM_DEBUG_DWLEN (1)
union pcompleter_ecpu_oprom_debug_u {
	struct pcompleter_ecpu_oprom_debug {
		u32 dbg:1;               /* [0] Default:0x0 RW */
		u32 Rsv:31;              /* [31:1] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_OPROM_DEBUG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_ERROR_ADDR  (0x100a000)
#define NBL_PCOMPLETER_ECPU_ERROR_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_ERROR_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_ERROR_DWLEN (1)
union pcompleter_ecpu_error_u {
	struct pcompleter_ecpu_error {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_ERROR_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_WARNING_ADDR  (0x100a004)
#define NBL_PCOMPLETER_ECPU_WARNING_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_WARNING_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_WARNING_DWLEN (1)
union pcompleter_ecpu_warning_u {
	struct pcompleter_ecpu_warning {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_WARNING_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CFG_ADDR  (0x100a048)
#define NBL_PCOMPLETER_ECPU_CFG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CFG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CFG_DWLEN (1)
union pcompleter_ecpu_cfg_u {
	struct pcompleter_ecpu_cfg {
		u32 dmux_fifo_drop_err:1; /* [0] Default:0x0 RC */
		u32 cif_axi_werr:1;      /* [1] Default:0x0 RC */
		u32 cif_axi_rerr:1;      /* [2] Default:0x0 RC */
		u32 cif_axi_ready_err:1; /* [3] Default:0x0 RC */
		u32 msg_axi_werr:1;      /* [4] Default:0x0 RC */
		u32 msg_axi_ready_err:1; /* [5] Default:0x0 RC */
		u32 rsv:26;              /* [31:6] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CFG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_DMUX_DEBUG_INFO_ADDR  (0x100a248)
#define NBL_PCOMPLETER_ECPU_DMUX_DEBUG_INFO_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_DMUX_DEBUG_INFO_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_DMUX_DEBUG_INFO_DWLEN (1)
union pcompleter_ecpu_dmux_debug_info_u {
	struct pcompleter_ecpu_dmux_debug_info {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_DMUX_DEBUG_INFO_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_DMUX_RAM_ERR_INFO_REG_ADDR  (0x100a24c)
#define NBL_PCOMPLETER_ECPU_DMUX_RAM_ERR_INFO_REG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_DMUX_RAM_ERR_INFO_REG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_DMUX_RAM_ERR_INFO_REG_DWLEN (1)
union pcompleter_ecpu_dmux_ram_err_info_reg_u {
	struct pcompleter_ecpu_dmux_ram_err_info_reg {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_DMUX_RAM_ERR_INFO_REG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MUX_DEBUG_INFO_ADDR  (0x100a700)
#define NBL_PCOMPLETER_ECPU_MUX_DEBUG_INFO_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MUX_DEBUG_INFO_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MUX_DEBUG_INFO_DWLEN (1)
union pcompleter_ecpu_mux_debug_info_u {
	struct pcompleter_ecpu_mux_debug_info {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MUX_DEBUG_INFO_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MUX_PORT_0_PRE_READ_DEBUG_REG_ADDR  (0x100a718)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_0_PRE_READ_DEBUG_REG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_0_PRE_READ_DEBUG_REG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_0_PRE_READ_DEBUG_REG_DWLEN (1)
union pcompleter_ecpu_mux_port_0_pre_read_debug_reg_u {
	struct pcompleter_ecpu_mux_port_0_pre_read_debug_reg {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MUX_PORT_0_PRE_READ_DEBUG_REG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MUX_PORT_1_PRE_READ_DEBUG_REG_ADDR  (0x100a71c)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_1_PRE_READ_DEBUG_REG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_1_PRE_READ_DEBUG_REG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_1_PRE_READ_DEBUG_REG_DWLEN (1)
union pcompleter_ecpu_mux_port_1_pre_read_debug_reg_u {
	struct pcompleter_ecpu_mux_port_1_pre_read_debug_reg {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MUX_PORT_1_PRE_READ_DEBUG_REG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MUX_PORT_2_PRE_READ_DEBUG_REG_ADDR  (0x100a720)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_2_PRE_READ_DEBUG_REG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_2_PRE_READ_DEBUG_REG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_2_PRE_READ_DEBUG_REG_DWLEN (1)
union pcompleter_ecpu_mux_port_2_pre_read_debug_reg_u {
	struct pcompleter_ecpu_mux_port_2_pre_read_debug_reg {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MUX_PORT_2_PRE_READ_DEBUG_REG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_MUX_PORT_3_PRE_READ_DEBUG_REG_ADDR  (0x100a724)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_3_PRE_READ_DEBUG_REG_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_3_PRE_READ_DEBUG_REG_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_MUX_PORT_3_PRE_READ_DEBUG_REG_DWLEN (1)
union pcompleter_ecpu_mux_port_3_pre_read_debug_reg_u {
	struct pcompleter_ecpu_mux_port_3_pre_read_debug_reg {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_MUX_PORT_3_PRE_READ_DEBUG_REG_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_CIF_AXIR_PRE_DEBUG_INFO_ADDR  (0x100a820)
#define NBL_PCOMPLETER_ECPU_CIF_AXIR_PRE_DEBUG_INFO_DEPTH (1)
#define NBL_PCOMPLETER_ECPU_CIF_AXIR_PRE_DEBUG_INFO_WIDTH (32)
#define NBL_PCOMPLETER_ECPU_CIF_AXIR_PRE_DEBUG_INFO_DWLEN (1)
union pcompleter_ecpu_cif_axir_pre_debug_info_u {
	struct pcompleter_ecpu_cif_axir_pre_debug_info {
		u32 dbg:32;              /* [31:0] Default:0x0 RO */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_CIF_AXIR_PRE_DEBUG_INFO_DWLEN];
} __packed;

#define NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_ADDR  (0x1018000)
#define NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_DEPTH (16)
#define NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_WIDTH (128)
#define NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_DWLEN (4)
union pcompleter_ecpu_qid_map_table_u {
	struct pcompleter_ecpu_qid_map_table {
		u32 max_qid:16;          /* [15:0] Default:0x0 RW */
		u32 base_qid:16;         /* [31:16] Default:0x0 RW */
		u32 Reserve0:8;          /* [39:32] Default:0x0 RO */
		u32 device_type:3;       /* [42:40] Default:0x0 RW */
		u32 Reserve1:5;          /* [47:43] Default:0x0 RO */
		u32 bar_addr_arr[2];     /* [111:48] Default:0x0 RW */
		u32 Reserve2:15;         /* [126:112] Default:0x0 RO */
		u32 valid:1;             /* [127] Default:0x0 RW */
	} __packed info;
	u32 data[NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_DWLEN];
} __packed;
#define NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_REG(r) (NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_ADDR + \
		(NBL_PCOMPLETER_ECPU_QID_MAP_TABLE_DWLEN *4) * (r))

#endif
